### ISSUE TITLE
Error trying to load gem middleman-bootstrap-navbar

### ISSUE THREAD

**Issue by torsybil** [bootstrap-ruby/middleman-bootstrap-navbar#3]
I am using middleman static website generation gem to develop a website. I want to include the bootstrap navbar into index file so i installed middleman-bootstrap-navbar gem.

Here is my **`config.rb`**

    configure :development do
      activate :livereload
      activate :bootstrap_navbar
      ready do
      sprockets.import_asset 'bootstrap.js'
    end
    configure :build do
     end

Here is my **`gemfile`**

    # Middleman Gems
    gem 'middleman', '>= 4.0.0'
    
    # Live-reloading plugin
    gem 'middleman-livereload'
    
    gem 'middleman-compass', '>= 4.0.0'
    
    # Navigation
    gem 'middleman-bootstrap-navbar'
    gem "sass"
    gem "bootstrap-sass", "~> 3.3.6", :require => false 
    gem 'sass-rails', '>=3.2'
    gem "jquery-middleman" #Don't forget to run 'bundle install'
    gem 'sprockets-rails', '~>3.0.0'

Here is my **`all.js`**

    //= require jquery  
    //= require bootstrap-sprockets
    //= require tree .

Here is my **`site.css.sass`**

    @import "bootstrap-sprockets";
    @import "normalize";
    @import "bootstrap";
    @charset "utf-8";

I Run bundle install after installing all necessary gems and restarted my server at LiveReload ip `bundle exec middleman`. I got this error afterwards:

[screenshot of the error in mysysgit][1]

please help.

**PS:** *Sorry I couldnt paste the error code here. That feature is not enabled in mysysgit bash.*

  [1]: http://i.stack.imgur.com/GeIaT.png

**Comment by manuelmeurer** [comment]
Well, I'm guessing that this has something to do with trying to run this on Windows... :smiley_cat: 
If you remove `middleman-bootstrap-navbar` from your Gemfile and `activate :bootstrap_navbar` from your config.rb, does everything else work then?
The error message from Bundler is pretty useless of course since it swallows the actual error message. Seems like this was only [fixed recently](https://github.com/bundler/bundler/issues/4182) so until Bundler > 1.11.2 is released, I can only guess what causes this error...

**Comment by Gochojr** [comment]
When I remove `middleman-bootstrap-navbar` from your Gemfile and `activate :bootstrap_navbar` from your config.rb, everything else works fine! I am using bundler > 1.11.2...

**Comment by sman591** [comment]
Having the same issue here. Removing `middleman-bootstrap-navbar` from my Gemfile doesn't fix it; I then get this error:

> /.../repo/vendor/ruby/2.1.0/gems/middleman-core-4.0.0/lib/middleman-core/extensions.rb:86:in `load': Unknown Extension: bootstrap_navbar. Check the name and make sure you have referenced the extension's gem in your Gemfile. (RuntimeError)
	from /.../repo/vendor/ruby/2.1.0/gems/middleman-core-4.0.0/lib/middleman-core/extension_manager.rb:49:in `activate'

**Comment by manuelmeurer** [comment]
@sman591 Are you on Windows as well?
Could you upload a small sample app so I can reproduce the error?

**Comment by sman591** [comment]
@manuelmeurer No, OS X. I can upload a sample app tomorrow

**Comment by manuelmeurer** [comment]
@sman591 @Gochojr What version of middleman-bootstrap-navbar are you using? Can you try to open a IRB or Pry session and simply require the gem there to see if that works?

**Comment by davidhrbac** [comment]
@manuelmeurer The very same here, brand new instance of Middleman.
> /home/hrb33/.rvm/gems/ruby-2.2.1/gems/middleman-core-4.1.2/lib/middleman-core/extensions.rb:86:in `load': Unknown Extension: bootstrap_navbar. Check the name and make sure you have referenced the extension's gem in your Gemfile. (RuntimeError)

config.rb:
```
activate :bootstrap_navbar
```

Gemfile
```
# If you do not have OpenSSL installed, change
# the following line to use 'http://'
source 'https://rubygems.org'

# For faster file watcher updates on Windows:
gem 'wdm', '~> 0.1.0', platforms: [:mswin, :mingw]

# Windows does not come with time zone data
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]

# Middleman Gems
gem 'middleman', '>= 4.0.0'
gem 'middleman-livereload'

gem 'therubyracer'

gem 'bootstrap-sass'
gem 'middleman-bootstrap-navbar'
gem 'jquery-middleman'
```

**Comment by manuelmeurer** [comment]
Sorry for the late response. Please try v3 which I just pushed, it should work with Middleman v3 and v4 now.
