### ISSUE TITLE
Items highlighted as active simultaneously when they are anchor links on the same page

### ISSUE THREAD

**Issue by cptncrnch** [bootstrap-ruby/middleman-bootstrap-navbar#4]
I'm currently using `middleman-bootstrap-navbar` to navigate a single scrolling page with anchor links that jump to sections on the page. I've realized that when the page loads initially, all of the anchor links are highlighted. None of the anchor tags have been reached when you're at the top of the page. As I scroll down, the correct item becomes active and continues to behave as expected throughout the page. When I return to the top, none of the items are highlighted (which is expected). When I reload the page, all anchor link items are again highlighted active.

Inspecting the page source code, I see when the page is first loaded that each `<li>` element has the `class: "active"` parameter.
```
<ul class="nav navbar-nav navbar-right">
      <li class="active">
      <a href="#home">
        Home
      </a>
    </li>
    <li class="active">
      <a href="#about">
        About
      </a>
    </li>
    <li class="active">
      <a href="#contact">
        Contact
      </a>
    </li>
</ul>
```

Is there a way to test for anchor links and have active items highlighted accordingly?

**Comment by manuelmeurer** [comment]
I'll close this for now. Feel free to reopen if you still have this problem!
